export const REQUEST_USER_DATA_FAILED = 'REQUEST_USER_DATA_FAILED';
export const REQUEST_USER_DATA_SUCCESS = 'REQUEST_USER_DATA_SUCCESS';

export const REG_INPUT_FIRST_NAME = 'REG_INPUT_FIRST_NAME';
export const REG_INPUT_LAST_NAME = 'REG_INPUT_LAST_NAME';
export const REG_INPUT_EMAIL = 'REG_INPUT_EMAIL';
export const REG_INPUT_PASSWORD = 'REG_INPUT_PASSWORD';

export const REG_SUCCESS = "REG_SUCCESS";
export const REG_FAILED = "REG_FAILED";
export const REG_LOADING = "REG_LOADING";

export const USER_LOGOUT = 'USER_LOGOUT'

export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';