const FLAGS = [
    {value: 'english', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./united-kingdom.png').default} /></div> },
    {value: 'egypt', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./egypt.png').default} /></div> },
    {value: 'esperanto', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./Esperanto.png').default} /></div> },
    {value: 'china', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./china.png').default} /></div> },
    {value: 'france', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./france.png').default} /></div>},
    {value: 'germany', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./germany.png').default} /></div>},
    {value: 'hungary', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./hungary.png').default} /></div>},
    {value: 'india', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./india.png').default} /></div> },
    {value: 'iran', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./iran.png').default} /></div> },
    {value: 'israel', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./israel.png').default} /></div> },
    {value: 'italy', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./italy.png').default} /></div>},
    {value: 'japan', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./japan.png').default} /></div>},
    {value: 'kurdish', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./Kurdish.png').default} /></div>},
    {value: 'netherlands', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./netherlands.png').default} /></div> },
    {value: 'norway', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./norway.png').default} /></div> },
    {value: 'pakistan', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./pakistan.png').default} /></div> },
    {value: 'philippines', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./philippines.png').default} /></div>},
    {value: 'portugal', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./portugal.png').default} /></div>},
    {value: 'poland', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./republic-of-poland.png').default} /></div>},
    {value: 'russia', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./russia.png').default} /></div> },
    {value: 'saudi', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./saudi-arabia.png').default} /></div> },
    {value: 'korea', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./south-korea.png').default} /></div> },
    {value: 'spain', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./spain.png').default} /></div>},
    {value: 'sweden', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./sweden.png').default} /></div>},
    {value: 'tanzania', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./tanzania.png').default} /></div>},
    {value: 'thailand', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./thailand.png').default} /></div> },
    {value: 'turkey', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./turkey.png').default} /></div> },
    {value: 'vietnam', label: <div><img alt="select-language"style={{width: '20.1px', height: '20.1px'}} src={require('./vietnam.png').default} /></div>},
]

export default FLAGS;

